/** 导出插件列表 */
export const pluginList = [
  {
    id: 1,
    name: "Plugin 1",
    shortName: "P1",
    description: "This is plugin 1",
    icon: "",
    path: "/plugin/p1.js",
  },
  {
    id: 2,
    name: "Plugin 2",
    shortName: "P2",
    description: "This is plugin 2",
    icon: "",
    path: "/plugin/p2.js",
  },
  {
    id: 3,
    name: "Plugin 3",
    shortName: "P3",
    description: "This is plugin 3",
    icon: "",
    path: "/plugin/p3.js",
  },
  {
    id: 4,
    name: "Plugin 4",
    shortName: "P4",
    description: "This is plugin 4",
    icon: "",
    path: "/plugin/p4.js",
  },
  {
    id: 5,
    name: "Plugin 5",
    shortName: "P5",
    description: "This is plugin 5",
    icon: "",
    path: "/plugin/p5.js",
  },
  {
    id: 6,
    name: "Plugin 6",
    shortName: "P6",
    description: "This is plugin 6",
    icon: "",
    path: "/plugin/p6.js",
  },
  {
    id: 7,
    name: "Plugin 7",
    shortName: "P7",
    description: "This is plugin 7",
    icon: "",
    path: "/plugin/p7.js",
  },
  {
    id: 8,
    name: "Plugin 8",
    shortName: "P8",
    description: "This is plugin 8",
    icon: "",
    path: "/plugin/p8.js",
  },
  {
    id: 9,
    name: "Plugin 9",
    shortName: "P9",
    description: "This is plugin 9",
    icon: "",
    path: "/plugin/p9.js",
  },
  {
    id: 10,
    name: "Plugin 10",
    shortName: "P10",
    description: "This is plugin 10",
    icon: "",
    path: "/plugin/p10.js",
  },
];
