export const generatedRoutes: GeneratedRoute[] = [
  {
    key: 0,
    name: "Home",
    path: "/home",
    layout: "layout.base",
    component: "pages.home",
    meta: {
      title: "home",
      // i18nKey: "route.home",
      i18nKey: "主页",
      icon: "home",
      order: 0,
    },
  },
  {
    key: 1,
    name: "About",
    path: "/about",
    layout: "layout.base",
    component: "pages.about",
    meta: {
      title: "about",
      i18nKey: "关于",
      icon: "about",
      order: 1,
    },
  },
  {
    key: 2,
    name: "Exception",
    path: "/exception",
    layout: "layout.base",
    meta: {
      title: "exception",
      i18nKey: "异常页",
      icon: "exception",
      order: 2,
    },
    children: [
      {
        key: 201,
        name: "403",
        path: "/exception/403",
        layout: "layout.base",
        component: "pages.exception.403",
        meta: {
          title: "403",
          i18nKey: "403",
          icon: "403",
          order: 0,
        },
      },
      {
        key: 202,
        name: "404",
        path: "/exception/404",
        layout: "layout.base",
        component: "pages.exception.404",
        meta: {
          title: "404",
          i18nKey: "404",
          icon: "404",
          order: 1,
        },
      },
      {
        key: 203,
        name: "500",
        path: "/exception/500",
        layout: "layout.base",
        component: "pages.exception.500",
        meta: {
          title: "500",
          i18nKey: "500",
          icon: "500",
          order: 2,
        },
      },
    ],
  },
  {
    key: 99,
    name: "Login",
    path: "/login",
    layout: "layout.blank",
    component: "pages.login",
    meta: {
      title: "login",
      i18nKey: "登录",
      icon: "login",
      order: 0,
    },
  },
];
